import 'dotenv/config';
import { drizzle } from 'drizzle-orm/postgres-js';
import postgres from 'postgres';
import { outreachContacts } from '../src/db/schema/outreach';

const client = postgres(process.env.DATABASE_URL!, { prepare: false });
const db = drizzle(client);

const leads = [
  // ============================================
  // ESTATE ATTORNEYS & TRUST/ESTATE PLANNING
  // ============================================
  {
    companyName: 'Gunster',
    contactName: 'Daniel A. Hanley',
    title: 'Shareholder, Private Wealth Services',
    phone: '(561) 650-0531',
    website: 'https://www.gunster.com',
    category: 'trust_estate_planning' as const,
    source: 'Web research',
    address: '777 South Flagler Drive, Suite 500 East',
    city: 'West Palm Beach',
    state: 'FL',
    notes: 'Historic Palm Beach firm. Strong T&E practice, family office attorneys. Florida\'s Law Firm for Leaders. Main: 800-749-1980',
  },
  {
    companyName: 'Jones Foster P.A.',
    contactName: '',
    title: '',
    phone: '(561) 659-3000',
    website: 'https://jonesfoster.com',
    category: 'trust_estate_planning' as const,
    source: 'Web research',
    address: '505 South Flagler Drive, Suite 1100',
    city: 'West Palm Beach',
    state: 'FL',
    notes: 'Serving Palm Beach County since 1924. Offices in WPB, Palm Beach, Jupiter. Private Wealth, Trusts & Estates practice with board-certified attorneys. Also has elder law practice.',
  },
  {
    companyName: 'Comiter, Singer, Baseman & Braun, LLP',
    contactName: 'Richard B. Comiter',
    title: 'Senior Partner',
    phone: '(561) 626-2101',
    website: 'https://www.comitersinger.com',
    category: 'trust_estate_planning' as const,
    source: 'Web research',
    address: '3801 PGA Blvd, Suite 604',
    city: 'Palm Beach Gardens',
    state: 'FL',
    notes: 'Tax Lawyer of the Year for WPB, Top 100 Attorneys in FL. Board-certified in tax and estate planning. Offices in PBG, Boca Raton, and Stuart.',
  },
  {
    companyName: 'Shutts & Bowen LLP',
    contactName: '',
    title: '',
    phone: '(305) 358-6300',
    website: 'https://www.shutts.com',
    category: 'trust_estate_planning' as const,
    source: 'Web research',
    address: '200 South Biscayne Blvd, Suite 2100',
    city: 'Miami',
    state: 'FL',
    notes: 'Full-service firm with offices across South FL (Miami, Fort Lauderdale, West Palm Beach). Strong T&E practice group.',
  },
  {
    companyName: 'Bilzin Sumberg',
    contactName: '',
    title: '',
    phone: '(305) 374-7580',
    website: 'https://www.bilzin.com',
    category: 'trust_estate_planning' as const,
    source: 'Web research',
    address: '1450 Brickell Avenue, 23rd Floor',
    city: 'Miami',
    state: 'FL',
    notes: 'Major Miami firm with dedicated T&E practice. Handles high-net-worth estate planning and administration.',
  },
  {
    companyName: 'Holland & Knight LLP',
    contactName: '',
    title: '',
    phone: '(305) 374-8500',
    website: 'https://www.hklaw.com',
    category: 'trust_estate_planning' as const,
    source: 'Web research',
    address: '701 Brickell Avenue, Suite 3300',
    city: 'Miami',
    state: 'FL',
    notes: 'AmLaw 100 firm with offices in Miami, Fort Lauderdale, West Palm Beach. Strong private wealth services and T&E practice.',
  },
  {
    companyName: 'Greenberg Traurig',
    contactName: '',
    title: '',
    phone: '(305) 579-0500',
    website: 'https://www.gtlaw.com',
    category: 'trust_estate_planning' as const,
    source: 'Web research',
    address: '333 SE 2nd Avenue, Suite 4400',
    city: 'Miami',
    state: 'FL',
    notes: 'Global firm HQ\'d in Miami. Large T&E team. Offices also in Boca Raton and Fort Lauderdale.',
  },
  {
    companyName: 'Akerman LLP',
    contactName: '',
    title: '',
    phone: '(305) 374-5600',
    website: 'https://www.akerman.com',
    category: 'trust_estate_planning' as const,
    source: 'Web research',
    address: '98 SE 7th Street, Suite 1100',
    city: 'Miami',
    state: 'FL',
    notes: 'Major FL-based firm. T&E practice with offices in Miami, Fort Lauderdale, West Palm Beach.',
  },
  {
    companyName: 'Chepenik Trushin LLP',
    contactName: '',
    title: '',
    phone: '(305) 374-1011',
    website: 'https://www.miamifloridaestateplanninglawyer.com',
    category: 'estate_attorney' as const,
    source: 'Web research',
    city: 'Miami',
    state: 'FL',
    notes: 'Unique blend of estate planning, probate, corporate/business law, and taxation. Serves Miami, Aventura, Miami Beach, Fort Lauderdale, Palm Beach.',
  },
  {
    companyName: 'SJF Law Group',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://estateandprobatelawyer.com',
    category: 'estate_attorney' as const,
    source: 'Web research',
    city: 'Fort Lauderdale',
    state: 'FL',
    notes: 'Since 2011, helping families across Fort Lauderdale, Miami, Boca Raton, and West Palm Beach with estate planning, probate & trust administration.',
  },
  {
    companyName: 'Moran & Associates',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://moran.law',
    category: 'trust_estate_planning' as const,
    source: 'Web research',
    city: 'Palm Beach',
    state: 'FL',
    notes: 'Serving Palm Beach County since 1975. Trusts & estates and real estate. Boutique firm.',
  },
  {
    companyName: 'Tribuiani Law Firm',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://www.tribuianilaw.com',
    category: 'trust_estate_planning' as const,
    source: 'Web research',
    city: 'Palm Beach Gardens',
    state: 'FL',
    notes: 'Full-service civil law firm. Wills and trusts, estate planning, probate and trust litigation, guardianships, asset protection.',
  },
  {
    companyName: 'Beacon Legacy Law',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://www.palmcitylawyer.com',
    category: 'estate_attorney' as const,
    source: 'Web research',
    city: 'Palm City',
    state: 'FL',
    notes: 'Estate planning, trust administration, probate, gun trusts. Serves Stuart/Martin County/Treasure Coast area.',
  },
  {
    companyName: 'Alex Gillen, Attorney at Law',
    contactName: 'Alex Gillen',
    title: 'Attorney',
    phone: '',
    website: 'https://agillen.com',
    category: 'estate_attorney' as const,
    source: 'Web research',
    city: 'Stuart',
    state: 'FL',
    notes: 'Wills, Trusts, Probate, Estate and Trust Administration, Real Estate Closings. Martin County focused.',
  },
  {
    companyName: 'Katz & Associates Law Firm',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://www.katzlawflorida.com',
    category: 'estate_attorney' as const,
    source: 'Web research',
    city: 'Stuart',
    state: 'FL',
    notes: 'Probate, Wills & Trusts. Offices in Stuart, Vero Beach, and Palm Beach.',
  },
  {
    companyName: 'The Castro Law Firm, PLLC',
    contactName: '',
    title: '',
    phone: '(855) 998-7570',
    website: 'https://www.tcastrolaw.com',
    category: 'estate_attorney' as const,
    source: 'Web research',
    city: 'West Palm Beach',
    state: 'FL',
    notes: 'Estate Planning. Consultation available in Boca Raton, Stuart, Royal Palm Beach, and Vero Beach.',
  },
  {
    companyName: 'Fox Rothschild LLP',
    contactName: '',
    title: '',
    phone: '(561) 835-9600',
    website: 'https://www.foxrothschild.com',
    category: 'trust_estate_planning' as const,
    source: 'Web research',
    city: 'West Palm Beach',
    state: 'FL',
    notes: 'National firm with FL presence. T&E group handles high-net-worth estate planning.',
  },
  {
    companyName: 'Proskauer Rose LLP',
    contactName: '',
    title: '',
    phone: '(561) 995-4777',
    website: 'https://www.proskauer.com',
    category: 'trust_estate_planning' as const,
    source: 'Web research',
    city: 'Boca Raton',
    state: 'FL',
    notes: 'Known for private client services. Strong personal planning department serving UHNW individuals.',
  },
  {
    companyName: 'The Siegel Law Group, P.A.',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://siegellawgroup.com',
    category: 'estate_attorney' as const,
    source: 'Web research',
    city: 'Boca Raton',
    state: 'FL',
    notes: '100+ combined years serving Boca Raton/South FL. Wills and Trusts, Elder Law, Medicaid Planning, Probate.',
  },
  {
    companyName: 'Berger Singerman LLP',
    contactName: '',
    title: '',
    phone: '(954) 525-9900',
    website: 'https://www.bergersingerman.com',
    category: 'estate_attorney' as const,
    source: 'Web research',
    city: 'Fort Lauderdale',
    state: 'FL',
    notes: 'FL-focused firm. Dispute resolution, business litigation. Offices in Fort Lauderdale, Miami, Boca Raton.',
  },
  {
    companyName: 'Ciklin Lubitz',
    contactName: '',
    title: '',
    phone: '(561) 832-5900',
    website: 'https://www.ciklinlubitz.com',
    category: 'estate_attorney' as const,
    source: 'Web research',
    city: 'West Palm Beach',
    state: 'FL',
    notes: 'Boutique firm. Estate litigation, probate, trust disputes.',
  },
  {
    companyName: 'GrayRobinson',
    contactName: '',
    title: '',
    phone: '(954) 761-8111',
    website: 'https://www.gray-robinson.com',
    category: 'trust_estate_planning' as const,
    source: 'Web research',
    city: 'Fort Lauderdale',
    state: 'FL',
    notes: 'Statewide FL firm. T&E practice. Offices in Fort Lauderdale and Miami.',
  },
  {
    companyName: 'Becker & Poliakoff',
    contactName: '',
    title: '',
    phone: '(954) 987-7550',
    website: 'https://www.becker-poliakoff.com',
    category: 'trust_estate_planning' as const,
    source: 'Web research',
    city: 'Fort Lauderdale',
    state: 'FL',
    notes: 'Well-known FL firm with offices across South Florida.',
  },
  {
    companyName: 'Morris Law Group',
    contactName: 'Stuart R. Morris',
    title: 'Board Certified Attorney, Wills/Trusts/Estates',
    phone: '',
    website: '',
    category: 'trust_estate_planning' as const,
    source: 'Web research',
    city: 'Boca Raton',
    state: 'FL',
    notes: 'Board Certified in Wills, Trusts & Estates. Estate and Gift Tax Planning, Business Succession Planning, Special Needs Planning.',
  },

  // ============================================
  // ELDER LAW
  // ============================================
  {
    companyName: 'Elder Needs Law, PLLC',
    contactName: 'Jason Neufeld',
    title: 'Board-Certified Elder Law Attorney',
    phone: '',
    website: 'https://www.elderneedslaw.com',
    category: 'elder_law' as const,
    source: 'Web research',
    city: 'Aventura',
    state: 'FL',
    notes: 'Offices in Aventura, Boca Raton, Plantation, Spring Hill. Elder law, Medicaid planning, estate planning in Miami-Dade & Broward.',
  },
  {
    companyName: 'Karp Law Firm',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://karplaw.com',
    category: 'elder_law' as const,
    source: 'Web research',
    city: 'Palm Beach Gardens',
    state: 'FL',
    notes: 'Florida estate planning, elder law, and probate attorneys.',
  },
  {
    companyName: 'Terner Elder Law, P.L.',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://www.ternerelderlaw.com',
    category: 'elder_law' as const,
    source: 'Web research',
    city: 'Boynton Beach',
    state: 'FL',
    notes: 'Special Needs, Disability, Elder Law. Serves Palm Beach County, Broward, Miami-Dade.',
  },
  {
    companyName: 'Millman Law Group',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://www.millmanlawgroup.com',
    category: 'elder_law' as const,
    source: 'Web research',
    city: 'Boca Raton',
    state: 'FL',
    notes: 'Elder law firm in Boca Raton. Medicaid planning, estate planning.',
  },
  {
    companyName: 'Cozen O\'Connor - Elder Law',
    contactName: '',
    title: '',
    phone: '(561) 750-3850',
    website: 'https://www.cozen.com',
    category: 'elder_law' as const,
    source: 'Web research',
    city: 'West Palm Beach',
    state: 'FL',
    notes: 'National firm with elder law practice. Probate in Palm Beach, Broward, Miami-Dade. Also reachable at 1-800-ELDERLAW.',
  },

  // ============================================
  // WEALTH MANAGEMENT & FAMILY OFFICES
  // ============================================
  {
    companyName: 'Glenmede - Palm Beach',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://www.glenmede.com/private-wealth-management/palm-beach/',
    category: 'wealth_management' as const,
    source: 'Web research',
    city: 'Palm Beach',
    state: 'FL',
    notes: 'Private wealth management. Team includes nationally recognized T&E attorney and former CIO of $1B family office.',
  },
  {
    companyName: 'Ulin & Co. Wealth Management',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://ulinwealth.com',
    category: 'family_office' as const,
    source: 'Web research',
    city: 'Boca Raton',
    state: 'FL',
    notes: 'Multi-family office for UHNW families. Serves Boca Raton, Delray Beach, Palm Beach. Investment strategy, tax planning, estate planning, risk management.',
  },
  {
    companyName: 'Gardens Wealth Management',
    contactName: '',
    title: '',
    phone: '',
    website: '',
    category: 'wealth_management' as const,
    source: 'Web research',
    city: 'Palm Beach Gardens',
    state: 'FL',
    notes: 'Established 2009. Over $3 billion in assets under management.',
  },
  {
    companyName: 'Corient Private Wealth',
    contactName: '',
    title: '',
    phone: '',
    website: '',
    category: 'wealth_management' as const,
    source: 'Web research',
    city: 'Miami',
    state: 'FL',
    notes: 'Top-rated financial advisor in FL. Serves HNW individuals, trusts, estates, personal holding companies, pension/profit-sharing plans.',
  },
  {
    companyName: 'StateTrust Wealth Management',
    contactName: '',
    title: '',
    phone: '',
    website: '',
    category: 'wealth_management' as const,
    source: 'Web research',
    city: 'Boca Raton',
    state: 'FL',
    notes: 'Privately held wealth management firm founded 2000. Serves HNW individuals, families, and organizations.',
  },
  {
    companyName: 'Morgan Stanley - Palm Beach Wealth Management Group',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://advisor.morganstanley.com/the-palm-beach-wealth-management-group',
    category: 'wealth_management' as const,
    source: 'Web research',
    city: 'Palm Beach Gardens',
    state: 'FL',
    notes: 'Portfolio management and family wealth planning. Also Boca Tropics Group and Royal Banyan Group in the area.',
  },

  // ============================================
  // BANK TRUST DEPARTMENTS
  // ============================================
  {
    companyName: 'Northern Trust - Palm Beach',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://www.northerntrust.com',
    category: 'bank_trust' as const,
    source: 'Web research',
    address: '440 Royal Palm Way',
    city: 'Palm Beach',
    state: 'FL',
    notes: 'Wealth management, asset management, asset servicing. Also office at 11301 US Hwy 1, North Palm Beach.',
  },
  {
    companyName: 'Bessemer Trust - Palm Beach',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://www.bessemertrust.com/offices/palm-beach-wealth-management',
    category: 'bank_trust' as const,
    source: 'Web research',
    city: 'Palm Beach',
    state: 'FL',
    notes: 'Founded 119+ years ago as a single family office. Investment management, wealth planning, family office services. Manages collections from $1M to $150M+.',
  },

  // ============================================
  // CPA / TAX SPECIALISTS
  // ============================================
  {
    companyName: 'Kaufman Rossin',
    contactName: 'Adrian Alfonso',
    title: 'Principal, Tax',
    phone: '',
    website: 'https://kaufmanrossin.com',
    category: 'cpa_tax' as const,
    source: 'Web research',
    city: 'Miami',
    state: 'FL',
    notes: 'One of largest CPA & advisory firms. Estate & Trust specialty. Offices in Miami, Fort Lauderdale, Boca Raton, Palm Beach. 20+ years serving HNW families. Specialized in estate planning tools (FLP, CLT, CRT, QPRT, GRAT).',
  },
  {
    companyName: 'Berkowitz Pollack Brant Advisors + CPAs',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://www.bpbcpa.com',
    category: 'cpa_tax' as const,
    source: 'Web research',
    city: 'Miami',
    state: 'FL',
    notes: 'Est. 1980. 425+ professionals. Offices in Miami, Fort Lauderdale, Boca Raton, West Palm Beach. Top 55 CPA firm in US. Estate and financial planning experts.',
  },
  {
    companyName: 'LerroSarbey Accounting & Advisory',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://lerrosarbey.com',
    category: 'cpa_tax' as const,
    source: 'Web research',
    city: 'Boca Raton',
    state: 'FL',
    notes: 'Full-service CPA firm in Boca Raton and Fort Lauderdale.',
  },

  // ============================================
  // DIVORCE / FAMILY LAW (HIGH NET WORTH)
  // ============================================
  {
    companyName: 'Rafool, PLLC',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://www.rafool.com',
    category: 'divorce_attorney' as const,
    source: 'Web research',
    city: 'Miami',
    state: 'FL',
    notes: 'Track record with high-net-worth and celebrity divorces. Equitable distribution, real estate division. Serves Miami, Fort Lauderdale, Palm Beach.',
  },
  {
    companyName: 'The Law Offices of Lawrence S. Katz, P.A.',
    contactName: 'Lawrence S. Katz',
    title: 'Founding Attorney',
    phone: '',
    website: 'https://www.katzfamilylaw.com',
    category: 'divorce_attorney' as const,
    source: 'Web research',
    city: 'Miami',
    state: 'FL',
    notes: 'High-asset divorce specialist. Serves affluent businesspeople, athletes, entertainment personalities in Miami.',
  },
  {
    companyName: 'Hamilton O\'Neill',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://www.hamiltonfamilylaw.com',
    category: 'divorce_attorney' as const,
    source: 'Web research',
    city: 'Miami',
    state: 'FL',
    notes: 'High-net-worth divorce. Protects financial futures, ensures equitable settlements. Miami-Dade, Palm Beach County, across South FL.',
  },
  {
    companyName: 'Gladstone, Weissman, Hirschberg & Schneider, P.A.',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://www.gwhslaw.com',
    category: 'divorce_attorney' as const,
    source: 'Web research',
    city: 'Boca Raton',
    state: 'FL',
    notes: 'High-asset divorce. Handles Palm Beach County, Broward County, Miami-Dade County. Complex asset evaluations.',
  },

  // ============================================
  // LUXURY REAL ESTATE
  // ============================================
  {
    companyName: 'Christian Angle Real Estate',
    contactName: 'Christian Angle',
    title: 'Broker',
    phone: '',
    website: 'https://anglerealestate.com',
    category: 'real_estate' as const,
    source: 'Web research',
    city: 'Palm Beach',
    state: 'FL',
    notes: 'Ranked #1 in Palm Beach. Over $1.1B sold in 2021. Specializes in oceanfront estates, luxury condos, private residences.',
  },
  {
    companyName: 'Lawrence Moens Associates',
    contactName: 'Lawrence Moens',
    title: 'Broker',
    phone: '',
    website: 'https://moensrealestate.com',
    category: 'real_estate' as const,
    source: 'Web research',
    city: 'Palm Beach',
    state: 'FL',
    notes: 'Palm Beach luxury homes specialist. Long-established boutique firm.',
  },
  {
    companyName: 'The Jills Zeder Group - Coldwell Banker',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://jillszeder.com',
    category: 'real_estate' as const,
    source: 'Web research',
    city: 'Miami Beach',
    state: 'FL',
    notes: 'Four decades of experience in Miami luxury real estate. Coldwell Banker Realty.',
  },
  {
    companyName: 'Brown Harris Stevens - Palm Beach',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://www.bhsusa.com',
    category: 'real_estate' as const,
    source: 'Web research',
    city: 'Palm Beach',
    state: 'FL',
    notes: 'Over 150 years in luxury real estate. NYC, Hamptons, Palm Beach, Miami. Often handles estate sales from luxury properties.',
  },
  {
    companyName: 'Dora Puig - Luxe Living Realty',
    contactName: 'Dora Puig',
    title: 'Broker',
    phone: '',
    website: 'https://dorapuig.com',
    category: 'real_estate' as const,
    source: 'Web research',
    city: 'Miami Beach',
    state: 'FL',
    notes: 'Ranked #1 luxury broker in Miami for 9 years. Over $5.8B in sales. Estate sales often involve art, antiques, jewelry.',
  },

  // ============================================
  // ESTATE LIQUIDATORS
  // ============================================
  {
    companyName: 'DejaVu Estate Liquidators',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://www.dejavuestateliquidators.com',
    category: 'estate_liquidator' as const,
    source: 'Web research',
    city: 'Palm Beach Gardens',
    state: 'FL',
    notes: 'Largest estate liquidator in South FL. Award-winning 20,000 sq ft showroom. Potential competitor but also referral partner.',
  },
  {
    companyName: 'The Estate Settlers',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://theestatesettlers.com',
    category: 'estate_liquidator' as const,
    source: 'Web research',
    city: 'Boca Raton',
    state: 'FL',
    notes: 'Estate liquidation, move coordination, property cleanouts. Palm Beach County and North Broward.',
  },
  {
    companyName: 'Estate Liquidators & Buyers Boca Raton',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://estateliquidatorsbocaraton.com',
    category: 'estate_liquidator' as const,
    source: 'Web research',
    city: 'Boca Raton',
    state: 'FL',
    notes: 'High-end jewelry (diamonds, gold, platinum), luxury watches (Rolex, Patek), antiques, full estates.',
  },
  {
    companyName: 'B & F Estate Sales',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://estatesalesfl.net',
    category: 'estate_liquidator' as const,
    source: 'Web research',
    city: 'Fort Lauderdale',
    state: 'FL',
    notes: 'Estate sales, liquidation, antique sales. Fort Lauderdale, Boca Raton, throughout South FL.',
  },
  {
    companyName: 'Estate Sales of South Florida',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://estatesalesofsouthflorida.com',
    category: 'estate_liquidator' as const,
    source: 'Web research',
    city: 'Palm Beach',
    state: 'FL',
    notes: 'Estate sales throughout South Florida.',
  },

  // ============================================
  // ART ADVISORS & INSURANCE
  // ============================================
  {
    companyName: 'Winston Art Group - Palm Beach',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://winstonartgroup.com',
    category: 'art_advisor' as const,
    source: 'Web research',
    city: 'Palm Beach',
    state: 'FL',
    notes: 'Art advisory and appraisal. Bridges Latin and South American collectors. Miami/Palm Beach office.',
  },
  {
    companyName: 'New York Fine Art Appraisers - Palm Beach',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://nyfaa.com/palm-beach/',
    category: 'art_advisor' as const,
    source: 'Web research',
    city: 'Palm Beach',
    state: 'FL',
    notes: 'Palm Beach office since 2013. Preferred provider for Chubb, AXA Art, PURE insurance. Fine and decorative art appraisals.',
  },
  {
    companyName: 'Private Art Consulting',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://www.privateartconsulting.com',
    category: 'art_advisor' as const,
    source: 'Web research',
    city: 'Miami',
    state: 'FL',
    notes: 'Miami-based. Fine art curation, procurement, strategic consulting, curatorial partnerships. NY and LA roots.',
  },
  {
    companyName: 'Estate Services & Appraisals',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://estateservicesappraisals.com',
    category: 'art_advisor' as const,
    source: 'Web research',
    city: 'Miami',
    state: 'FL',
    notes: 'Estates and Fine Art Appraisals Valuations. Corporate & Individual Collection Consultants.',
  },
  {
    companyName: 'PURE Insurance - Art Services',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://www.pureinsurance.com',
    category: 'insurance' as const,
    source: 'Web research',
    city: 'Palm Beach',
    state: 'FL',
    notes: 'Art insurance for collections $1M-$150M+. Inventory/database creation, appraisal management, shipping/conservation. Palm Beach office.',
  },
  {
    companyName: 'Southeast Insurance Group',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://southeastinsure.com',
    category: 'insurance' as const,
    source: 'Web research',
    city: 'South Florida',
    state: 'FL',
    notes: 'Fine art and collectibles insurance. Works with galleries, museums, private collections. Valuations, care, storage, transportation.',
  },
];

async function seed() {
  console.log(`Seeding ${leads.length} outreach leads...`);

  for (const lead of leads) {
    await db.insert(outreachContacts).values({
      companyName: lead.companyName,
      contactName: lead.contactName || null,
      title: lead.title || null,
      email: lead.email || null,
      phone: lead.phone || null,
      website: lead.website || null,
      category: lead.category,
      source: lead.source,
      address: lead.address || null,
      city: lead.city || null,
      state: lead.state || null,
      notes: lead.notes || null,
    });
  }

  console.log('Done! Seeded all outreach leads.');
  process.exit(0);
}

seed().catch((err) => {
  console.error('Seed error:', err);
  process.exit(1);
});
