import 'dotenv/config';
import { drizzle } from 'drizzle-orm/postgres-js';
import postgres from 'postgres';
import { outreachContacts } from '../src/db/schema/outreach';
import { sql } from 'drizzle-orm';

const client = postgres(process.env.DATABASE_URL!, { prepare: false });
const db = drizzle(client);

const leads = [
  // ============================================
  // NAPLES / MARCO ISLAND / BONITA SPRINGS / FORT MYERS
  // ============================================

  // --- Estate Attorneys & Trust/Estate Planning ---
  {
    companyName: 'Wollman, Gehrke & Associates, P.A.',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://www.probate-florida.com',
    category: 'trust_estate_planning' as const,
    source: 'Web research',
    city: 'Naples',
    state: 'FL',
    notes: 'Trust administration, asset protection, art law. Served Naples, Marco Island, Bonita Springs for 20+ years.',
  },
  {
    companyName: 'Quarles & Brady LLP - Naples',
    contactName: 'Kimberly Leach Johnson',
    title: 'Partner, Estate & Trust',
    phone: '',
    website: 'https://www.quarles.com',
    category: 'trust_estate_planning' as const,
    source: 'Web research',
    city: 'Naples',
    state: 'FL',
    notes: '35+ years advising HNW individuals and families. Full range of estate planning and trust administration.',
  },
  {
    companyName: 'Bond, Schoeneck & King PLLC - Naples',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://www.bsk.com',
    category: 'trust_estate_planning' as const,
    source: 'Web research',
    city: 'Naples',
    state: 'FL',
    notes: 'HNW trust and estate planning, tax compliance, financial planning, probate and trust litigation.',
  },
  {
    companyName: 'Linde, Gould & Associates',
    contactName: 'Matthew A. Linde',
    title: 'Board Certified Elder Law & Wills/Trusts/Estates',
    phone: '(239) 939-7100',
    website: 'https://www.floridaprobatelitigator.com',
    category: 'estate_attorney' as const,
    source: 'Web research',
    city: 'Fort Myers',
    state: 'FL',
    notes: 'One of only 10 FL lawyers board certified in both Elder Law and Wills/Trusts/Estates. Only one in SW FL with dual certification. Serves Fort Myers, Cape Coral, Bonita Springs, Naples, Marco Island.',
  },
  {
    companyName: 'Safe Harbor Law Firm',
    contactName: 'Pam Buff Baker',
    title: 'Founder, Board-Certified Elder Law Attorney',
    phone: '(239) 977-5158',
    website: 'https://safeharborlawfirm.com',
    category: 'elder_law' as const,
    source: 'Web research',
    city: 'Naples',
    state: 'FL',
    notes: 'Offices in Naples and Bonita Springs. Estate planning, elder law, probate, trust administration, Medicaid planning.',
  },
  {
    companyName: 'Skrivan & Gibbs PLLC',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://sgnapleslaw.com',
    category: 'trust_estate_planning' as const,
    source: 'Web research',
    city: 'Naples',
    state: 'FL',
    notes: 'Tax, estate planning, real estate, trusts, probate. Serves Naples, Bonita Springs, Fort Myers, Marco Island.',
  },
  {
    companyName: 'Threlkeld Law',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://www.napleslegal.net',
    category: 'estate_attorney' as const,
    source: 'Web research',
    city: 'Naples',
    state: 'FL',
    notes: 'Real estate, estate planning, title insurance. Serves Collier County and Lee County.',
  },
  {
    companyName: 'Martin Law Firm',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://www.martinlawfirm.com',
    category: 'estate_attorney' as const,
    source: 'Web research',
    city: 'Naples',
    state: 'FL',
    notes: 'Estate & trust litigation in Southwest Florida.',
  },
  {
    companyName: 'Burzynski Elder Law',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://burzynskilaw.com',
    category: 'elder_law' as const,
    source: 'Web research',
    city: 'Naples',
    state: 'FL',
    notes: 'Estate planning, Medicaid, life care planning, probate, guardianship. Naples-based.',
  },
  {
    companyName: 'Hampton Law',
    contactName: '',
    title: '',
    phone: '(239) 309-0090',
    website: 'https://www.hamptonelderlaw.com',
    category: 'elder_law' as const,
    source: 'Web research',
    city: 'Fort Myers',
    state: 'FL',
    notes: 'Estate planning, estate administration, elder law, Medicaid planning.',
  },
  {
    companyName: 'Osterhout & McKinney, PA',
    contactName: 'Julie Osterhout',
    title: 'Founding Attorney',
    phone: '',
    website: 'https://osterhoutmckinney.com',
    category: 'elder_law' as const,
    source: 'Web research',
    address: '999 Vanderbilt Road, Suite 200',
    city: 'Naples',
    state: 'FL',
    notes: 'Founded 1990. Protecting elderly assets and security. Daily Medicaid work. Also Fort Myers office at 3783 Seago Lane.',
  },

  // --- Wealth Management & Bank Trust (Naples/SWFL) ---
  {
    companyName: 'Bessemer Trust - Naples',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://www.bessemertrust.com/offices/naples-wealth-management',
    category: 'bank_trust' as const,
    source: 'Web research',
    city: 'Naples',
    state: 'FL',
    notes: 'Investment management, wealth planning, family office services. 119+ year old multi-family office.',
  },
  {
    companyName: 'Northern Trust - Naples (Tamiami)',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://www.northerntrust.com',
    category: 'bank_trust' as const,
    source: 'Web research',
    address: '4001 Tamiami Trail North',
    city: 'Naples',
    state: 'FL',
    notes: 'Wealth management, asset management, asset servicing. Also downtown office at 500 Fifth Avenue South.',
  },
  {
    companyName: 'BNY Wealth - Naples',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://www.bny.com/wealth',
    category: 'bank_trust' as const,
    source: 'Web research',
    city: 'Naples',
    state: 'FL',
    notes: 'Trust and estate services. Expert fiduciary solutions, trust administration, estate planning.',
  },
  {
    companyName: 'Legacy Family Office',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://www.legacyfamilyoffice.com',
    category: 'family_office' as const,
    source: 'Web research',
    address: '9990 Coconut Road, Suite 225',
    city: 'Bonita Springs',
    state: 'FL',
    notes: 'Multi-family office and registered investment adviser. Southwest Florida wealth management.',
  },
  {
    companyName: 'Florida Trust Company',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://floridatrust.com',
    category: 'bank_trust' as const,
    source: 'Web research',
    city: 'Naples',
    state: 'FL',
    notes: 'Serves Sanibel/Captiva, Fort Myers, Naples, Marco Island. Family office services including family education, governance, philanthropy, succession planning.',
  },
  {
    companyName: 'Nova Wealth Management',
    contactName: '',
    title: '',
    phone: '(888) 677-9910',
    website: 'https://novawealthmanagement.com',
    category: 'wealth_management' as const,
    source: 'Web research',
    address: '24311 Walden Center Dr, Suite 200',
    city: 'Bonita Springs',
    state: 'FL',
    notes: 'Serves Bonita Springs, Naples, Fort Myers, Marco Island, Estero.',
  },

  // --- CPAs (Naples) ---
  {
    companyName: 'Dee & Associates CPAs',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://deecpa.com',
    category: 'cpa_tax' as const,
    source: 'Web research',
    city: 'Naples',
    state: 'FL',
    notes: 'Premier CPA firm in Naples since 1976. Personalized trust and estate planning for HNW and UHNW individuals and affluent families.',
  },
  {
    companyName: 'Garcia & Carlson CPA, PA',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://www.garciacarlson.com',
    category: 'cpa_tax' as const,
    source: 'Web research',
    city: 'Naples',
    state: 'FL',
    notes: 'Tax, estate planning, business consulting. HNW individuals, affluent families. Work with families and attorneys on tax-efficient wealth transfer.',
  },
  {
    companyName: 'Davidson & Nick CPAs',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://www.dncpas.com',
    category: 'cpa_tax' as const,
    source: 'Web research',
    city: 'Naples',
    state: 'FL',
    notes: 'Estate and trust tax services. Proactive tax planning for significant savings.',
  },
  {
    companyName: 'CCG Certified Public Accountants',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://www.ccgcpas.com',
    category: 'cpa_tax' as const,
    source: 'Web research',
    city: 'Naples',
    state: 'FL',
    notes: 'Full service tax, accounting, business consulting. Estate & trust tax services.',
  },

  // --- Divorce (Naples) ---
  {
    companyName: 'Long, Murphy & Zung, P.A.',
    contactName: '',
    title: '',
    phone: '(239) 232-2208',
    website: 'https://www.naplesfamilylawfirm.com',
    category: 'divorce_attorney' as const,
    source: 'Web research',
    city: 'Naples',
    state: 'FL',
    notes: 'Two board-certified marital and family law attorneys. High-asset divorce, thorough asset assessment.',
  },
  {
    companyName: 'Bergermann Law Firm',
    contactName: '',
    title: '',
    phone: '(239) 334-0075',
    website: 'https://bergermannlaw.com',
    category: 'divorce_attorney' as const,
    source: 'Web research',
    city: 'Fort Myers',
    state: 'FL',
    notes: 'High-asset divorce. Asset-protection strategies tailored to FL law. Also serves Cape Coral and Naples.',
  },
  {
    companyName: 'Silverio & Hall, PA',
    contactName: '',
    title: '',
    phone: '(239) 649-1001',
    website: 'https://www.silveriohall.com',
    category: 'divorce_attorney' as const,
    source: 'Web research',
    city: 'Naples',
    state: 'FL',
    notes: 'Family law and divorce. Equitable distribution of assets and liabilities. Divorce often involves art, antiques, jewelry valuation.',
  },

  // --- Luxury Real Estate (Naples) ---
  {
    companyName: 'Gulf Coast International Properties',
    contactName: '',
    title: '',
    phone: '(239) 434-2558',
    website: 'https://www.gcipnaples.com',
    category: 'real_estate' as const,
    source: 'Web research',
    city: 'Naples',
    state: 'FL',
    notes: 'Premier luxury realty. 100+ years combined experience. Naples waterfront homes specialist.',
  },
  {
    companyName: 'Dante DiSabato - William Raveis Real Estate',
    contactName: 'Dante DiSabato',
    title: 'Luxury Agent',
    phone: '',
    website: 'https://www.dantedisabato.com',
    category: 'real_estate' as const,
    source: 'Web research',
    city: 'Naples',
    state: 'FL',
    notes: '$1B+ in sales in 12 years. Top 10 of 4,600 agents at William Raveis. Encounters estate sales regularly.',
  },
  {
    companyName: 'The Resop Team',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://theresopteam.com',
    category: 'real_estate' as const,
    source: 'Web research',
    city: 'Naples',
    state: 'FL',
    notes: '$1.2B+ in sales in under 10 years. Luxury Naples properties.',
  },

  // --- Estate Liquidators & Art Advisors (Naples/SWFL) ---
  {
    companyName: 'Prestige Estate Services - Naples',
    contactName: 'Alicia Weaver',
    title: 'ISA Certified Appraiser',
    phone: '',
    website: 'https://prestigeestateservices.com',
    category: 'art_advisor' as const,
    source: 'Web research',
    city: 'Naples',
    state: 'FL',
    notes: '75+ years combined experience. Fine art, antique furniture, sports collectibles, household appraisals. ISA and AAA accredited. Serves Sarasota through Marco Island.',
  },
  {
    companyName: 'Anubis Appraisal & Estate Services',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://www.anubisappraisal.com',
    category: 'estate_liquidator' as const,
    source: 'Web research',
    city: 'Naples',
    state: 'FL',
    notes: 'Art valuations, art advisor, antiques appraisals, fine art appraisals, liquidation. Serves Naples, Fort Myers, Sarasota.',
  },
  {
    companyName: 'Freeman\'s - Naples',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://freemansauction.com/locations/naples',
    category: 'estate_liquidator' as const,
    source: 'Web research',
    city: 'Naples',
    state: 'FL',
    notes: 'Est. 2010. Full-service appraisal and estate support. Category specialists in Fine Art, Jewelry, Furniture, Decorative Arts. Competitor but potential referral partner.',
  },
  {
    companyName: 'Estate Liquidators Naples Florida',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://estateliquidatorsnaples.com',
    category: 'estate_liquidator' as const,
    source: 'Web research',
    city: 'Naples',
    state: 'FL',
    notes: 'Estate buyers and liquidators in Naples area. Antique buyers.',
  },

  // ============================================
  // SARASOTA / LONGBOAT KEY / SIESTA KEY
  // ============================================
  {
    companyName: 'Band Law Group',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://www.bandlawgroup.com',
    category: 'trust_estate_planning' as const,
    source: 'Web research',
    city: 'Sarasota',
    state: 'FL',
    notes: 'Estate planning and probate. Clients include business owners, professionals, executives, retirees, and HNW individuals. Wealth preservation and generational transfer.',
  },
  {
    companyName: 'David P. Johnson, P.A.',
    contactName: 'David P. Johnson',
    title: 'Board Certified Tax Law & Wills/Trusts/Estates',
    phone: '',
    website: 'https://fl-estateplanning.com',
    category: 'trust_estate_planning' as const,
    source: 'Web research',
    city: 'Sarasota',
    state: 'FL',
    notes: 'One of only 38 of FL\'s 100,000 attorneys certified in both Tax Law and Wills/Trusts/Estates. Estate planning, probate, business law.',
  },
  {
    companyName: 'Ledbetter Cowan Law Group',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://www.ledbetterlawfl.com',
    category: 'trust_estate_planning' as const,
    source: 'Web research',
    city: 'Venice',
    state: 'FL',
    notes: 'Estate planning, wills, trusts, probate, asset protection, charitable planning. Serves Venice, Sarasota, Longboat Key, Casey Key, Siesta Key, Boca Grande.',
  },
  {
    companyName: 'Teresa K. Bowman P.A.',
    contactName: 'Teresa K. Bowman',
    title: 'Certified Elder Law Attorney',
    phone: '',
    website: 'https://www.tkbowmanpa.com',
    category: 'elder_law' as const,
    source: 'Web research',
    city: 'Sarasota',
    state: 'FL',
    notes: 'Elder law and estate planning. Serves Sarasota, Longboat Key, Bradenton, Nokomis, Osprey, Manatee County.',
  },
  {
    companyName: 'Berlin Patten Ebling - Sarasota',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://berlinpatten.com',
    category: 'trust_estate_planning' as const,
    source: 'Web research',
    city: 'Sarasota',
    state: 'FL',
    notes: 'Estate planning, wills, revocable and irrevocable trusts. Asset protection and long-term planning.',
  },
  {
    companyName: 'Dunlap Moran',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://dunlapmoran.com',
    category: 'trust_estate_planning' as const,
    source: 'Web research',
    city: 'Sarasota',
    state: 'FL',
    notes: 'Corporate/business, estate planning, probate, tax, real estate. Serves Sarasota, Lakewood Ranch, Siesta Key.',
  },
  {
    companyName: 'Schipani Law Group, P.A.',
    contactName: '',
    title: '',
    phone: '(941) 499-8154',
    website: 'https://www.manasotalawyer.com',
    category: 'divorce_attorney' as const,
    source: 'Web research',
    city: 'Sarasota',
    state: 'FL',
    notes: 'Board-Certified in Matrimonial and Family Law. High net worth divorce. Asset distribution involving art, antiques, jewelry.',
  },
  {
    companyName: 'Boeller Law, P.A.',
    contactName: '',
    title: '',
    phone: '(941) 315-8598',
    website: 'https://www.boellerlaw.com',
    category: 'divorce_attorney' as const,
    source: 'Web research',
    city: 'Sarasota',
    state: 'FL',
    notes: 'High net worth divorce. Equitable asset distribution. Protects rights and interests.',
  },
  {
    companyName: 'Northern Trust - Sarasota',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://www.northerntrust.com',
    category: 'bank_trust' as const,
    source: 'Web research',
    address: '1515 Ringling Boulevard',
    city: 'Sarasota',
    state: 'FL',
    notes: 'Wealth management, asset management, asset servicing.',
  },
  {
    companyName: 'Alla Johnson CPA LLC',
    contactName: 'Alla Johnson',
    title: 'CPA, Estate/Trust Specialist',
    phone: '',
    website: 'https://www.allajohnson.com',
    category: 'cpa_tax' as const,
    source: 'Web research',
    city: 'Sarasota',
    state: 'FL',
    notes: 'Fiduciary accounting, trust/estate tax, money-saving strategies. Serves Sarasota area.',
  },
  {
    companyName: 'Antiques Gallery of Sarasota',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://www.antiquesgalleryofsarasota.com',
    category: 'estate_liquidator' as const,
    source: 'Web research',
    city: 'Sarasota',
    state: 'FL',
    notes: 'Largest purchaser of fine art on FL west coast. In-house certified appraisals for estate and insurance purposes.',
  },

  // ============================================
  // CORAL GABLES / KEY BISCAYNE / COCONUT GROVE
  // ============================================
  {
    companyName: 'Trust Counsel, PL',
    contactName: '',
    title: '',
    phone: '(305) 707-7126',
    website: 'https://trustcounsel.com',
    category: 'trust_estate_planning' as const,
    source: 'Web research',
    city: 'Coral Gables',
    state: 'FL',
    notes: 'Estate planning for wills, trusts, probate, business succession, asset protection. Coral Gables location.',
  },
  {
    companyName: 'Veliz & Associates, P.A.',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://velizlaw.com',
    category: 'trust_estate_planning' as const,
    source: 'Web research',
    city: 'Coral Gables',
    state: 'FL',
    notes: '35+ years protecting families and hard-earned assets. Business succession planning. Coral Gables.',
  },
  {
    companyName: 'Sullivan, Admire & Sullivan, P.A.',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://www.sullivanadmire.com',
    category: 'trust_estate_planning' as const,
    source: 'Web research',
    city: 'Coral Gables',
    state: 'FL',
    notes: 'Family-operated law firm serving Coral Gables community and South Florida since 1923. Estate planning & probate.',
  },
  {
    companyName: 'The Estate Plan FL',
    contactName: '',
    title: '',
    phone: '(305) 677-8489',
    website: 'https://www.theestateplanfl.com',
    category: 'estate_attorney' as const,
    source: 'Web research',
    city: 'Coral Gables',
    state: 'FL',
    notes: 'Estate planning, estate administration & litigation, trust administration. Coral Gables.',
  },
  {
    companyName: 'Perlin Estate Planning & Probate',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://perlinestateplanning.com',
    category: 'estate_attorney' as const,
    source: 'Web research',
    city: 'Miami',
    state: 'FL',
    notes: 'Founded 1985. Estate planning, probate, trust administration, elder law. Coral Gables area.',
  },
  {
    companyName: 'Lavender Greenberg PLLC',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://lglawmiami.com',
    category: 'trust_estate_planning' as const,
    source: 'Web research',
    city: 'Coral Gables',
    state: 'FL',
    notes: 'Estate Planning, Probate & Guardianship. Client-centered firm in center of Coral Gables.',
  },
  {
    companyName: 'Parent Your Parents',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://parentyourparents.com',
    category: 'elder_law' as const,
    source: 'Web research',
    city: 'Miami',
    state: 'FL',
    notes: 'Serves Miami, Key Biscayne, Pinecrest, South Miami, Coral Gables, Coconut Grove. Estate planning.',
  },

  // ============================================
  // TAMPA BAY / ST. PETE / CLEARWATER
  // ============================================
  {
    companyName: 'Fisher and Wilsey, P.A.',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://www.fisher-wilsey-law.com',
    category: 'trust_estate_planning' as const,
    source: 'Web research',
    city: 'St. Petersburg',
    state: 'FL',
    notes: '60+ years creating estate plans for St. Pete, Clearwater, Tampa and surrounding areas.',
  },
  {
    companyName: 'Baskin Eisel Rightmyer',
    contactName: '',
    title: '',
    phone: '',
    website: 'http://baskineisel.com',
    category: 'estate_attorney' as const,
    source: 'Web research',
    city: 'Clearwater',
    state: 'FL',
    notes: 'Contested estate, trust, and guardianship matters. Clearwater, St. Pete, Tampa, Pinellas and Hillsborough County.',
  },
  {
    companyName: 'Legacy Protection Lawyers',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://www.legacyprotectionlawyers.com',
    category: 'trust_estate_planning' as const,
    source: 'Web research',
    city: 'St. Petersburg',
    state: 'FL',
    notes: 'Estate planning, probate, trust administration, will and trust litigation. Tampa Bay area.',
  },
  {
    companyName: 'Mortellaro Law',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://www.mortellarolaw.com',
    category: 'elder_law' as const,
    source: 'Web research',
    city: 'St. Petersburg',
    state: 'FL',
    notes: 'Estate planning and elder law. Offices in St. Pete and Clearwater. Tampa Bay area.',
  },
  {
    companyName: 'Harris, Hunt & Derr, P.A.',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://www.harrishuntderr.com',
    category: 'divorce_attorney' as const,
    source: 'Web research',
    city: 'Tampa',
    state: 'FL',
    notes: 'High-asset divorce specialist. Tampa Bay area. Complex asset evaluations, art, jewelry, antiques in equitable distribution.',
  },

  // ============================================
  // PONTE VEDRA / AMELIA ISLAND / JACKSONVILLE
  // ============================================
  {
    companyName: 'Fisher, Tousey, Leas & Ball, P.A.',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://www.fishertousey.com',
    category: 'trust_estate_planning' as const,
    source: 'Web research',
    city: 'Jacksonville',
    state: 'FL',
    notes: 'Offices in Jacksonville, Amelia Island, Ponte Vedra. 30+ years serving HNW clients. Estate planning, probate, trust administration.',
  },
  {
    companyName: 'Rock Solid Law & Title',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://www.rocksolidlaw.com',
    category: 'trust_estate_planning' as const,
    source: 'Web research',
    city: 'Ponte Vedra Beach',
    state: 'FL',
    notes: '30+ years in estate planning, probate, trust administration. Helps FL families plan and preserve wealth.',
  },
  {
    companyName: 'Blackburn & Company, L.C.',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://www.blackburnandco.com',
    category: 'trust_estate_planning' as const,
    source: 'Web research',
    city: 'Jacksonville',
    state: 'FL',
    notes: 'Trusts & estates. Asset transfer strategy, tax minimization, guardianship, philanthropy. Estate analysis.',
  },
  {
    companyName: 'Rise Up Legal',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://riseuplegal.com',
    category: 'estate_attorney' as const,
    source: 'Web research',
    city: 'Jacksonville Beach',
    state: 'FL',
    notes: 'Wills, trusts, probate, trust administration, asset protection. Serves Ponte Vedra Beach and NE Florida.',
  },
  {
    companyName: 'Mason Law Firm, P.A.',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://www.lawyer-jacksonville.com',
    category: 'estate_attorney' as const,
    source: 'Web research',
    city: 'Ponte Vedra Beach',
    state: 'FL',
    notes: 'Estate planning attorney. Ponte Vedra Beach and Jacksonville area.',
  },

  // ============================================
  // ORLANDO / WINTER PARK
  // ============================================
  {
    companyName: 'Giles & Robinson, P.A.',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://gilesrobinson.com',
    category: 'trust_estate_planning' as const,
    source: 'Web research',
    city: 'Orlando',
    state: 'FL',
    notes: '115+ years of service. Estate planning, probate administration. Orlando and Central Florida.',
  },
  {
    companyName: 'Bogin Munns & Munns',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://www.boginmunns.com',
    category: 'trust_estate_planning' as const,
    source: 'Web research',
    city: 'Orlando',
    state: 'FL',
    notes: 'Serving Floridians since 1979. Wills, trusts, estate plans, probate. Orange, Seminole, Osceola Counties and Central FL retirement communities.',
  },
  {
    companyName: 'Jackson Law PA',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://www.jacksonlawpa.com',
    category: 'estate_attorney' as const,
    source: 'Web research',
    city: 'Orlando',
    state: 'FL',
    notes: '75+ years collective experience. Probate and estate planning. Wills, trusts, probate services.',
  },

  // ============================================
  // INSURANCE (Statewide / SWFL)
  // ============================================
  {
    companyName: 'Sexton & Schnoll CPAs',
    contactName: '',
    title: '',
    phone: '',
    website: 'https://www.sextonandschnoll.com',
    category: 'cpa_tax' as const,
    source: 'Web research',
    city: 'Naples',
    state: 'FL',
    notes: 'High net worth tax planning, estate and trust specialty. Florida CPA firm.',
  },
];

async function seed() {
  // Check existing count first
  const existing = await db.execute(sql`SELECT count(*) as cnt FROM outreach_contacts`);
  console.log(`Existing leads: ${existing[0].cnt}`);

  console.log(`Seeding ${leads.length} new outreach leads (Florida-wide expansion)...`);

  let added = 0;
  for (const lead of leads) {
    // Skip if company already exists
    const [dup] = await db.execute(
      sql`SELECT id FROM outreach_contacts WHERE company_name = ${lead.companyName} LIMIT 1`
    );
    if (dup) {
      console.log(`  SKIP (duplicate): ${lead.companyName}`);
      continue;
    }

    await db.insert(outreachContacts).values({
      companyName: lead.companyName,
      contactName: lead.contactName || null,
      title: lead.title || null,
      email: null,
      phone: lead.phone || null,
      website: lead.website || null,
      category: lead.category,
      source: lead.source,
      address: lead.address || null,
      city: lead.city || null,
      state: lead.state || null,
      notes: lead.notes || null,
    });
    added++;
  }

  const final = await db.execute(sql`SELECT count(*) as cnt FROM outreach_contacts`);
  console.log(`\nAdded ${added} new leads. Total: ${final[0].cnt}`);
  process.exit(0);
}

seed().catch((err) => {
  console.error('Seed error:', err);
  process.exit(1);
});
